import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedCategories() {
  await prisma.category.createMany({
    data: [
      {name: "T-shirts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Shirts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Blouses", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Tank tops", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Polo shirts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Jeans", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Sweatpants", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Dress pants", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Shorts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Skirts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Dresses", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Jumpsuits", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Overalls", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Sets", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Sweaters", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Cardigans", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Jackets", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Coats", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Blazers", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Undergarments", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Socks", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Swimwear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Sportswear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Activewear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Sleepwear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Outerwear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Accessories", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Kids’ clothing", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Plus-size clothing", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Hoodies", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Formal shirts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Casual shirts", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Crop tops", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Hooded jackets", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Windbreakers", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Cargo pants", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Capri pants", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Joggers", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Trousers", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Leggings", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Bodysuits", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Rompers", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Business suits", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Overcoats", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Vests", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Loungewear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Festival wear", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Graphic tees", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Fashion tops", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
      {name: "Basic tees", picture: "https://ph-cdn3.ecosweb.com.br/Web/posthaus/mobile/menu/03_128.png" },
    ],
  });
}
